const nameOnPass = "Sruti Swaminathan";
console.log("Passenger Name: " + nameOnPass);
const nameOnId = "Sruti Swaminathan";
const nameMatch = nameOnPass === nameOnId;
console.log("ID confirmed? " + nameMatch);
const length = 30;
const doesLengthPass = length < 30;
const height = 56;
doesHeightPass = height < 55;
const isHandBaggageEligible = doesLengthPass && doesHeightPass;
console.log("Is Hand Baggage Eligible? " + isHandBaggageEligible);
const flightDes = "Dallas";
const returnFrom = "Phoenix";
const isRoundTrip = flightDes === returnFrom;
console.log("Round Trip Check? " + isRoundTrip);
const bookings = 2;
const totalCapacity = 100;
const isFlightAvailable = bookings < totalCapacity;
console.log("Are seats available? " + isFlightAvailable);
document.querySelector("#name").innerHTML = nameOnPass;
document.querySelector("#id").innerHTML = nameMatch;
document.querySelector("#bag").innerHTML = isHandBaggageEligible;
document.querySelector("#des").innerHTML = isRoundTrip;
document.querySelector("#seat").innerHTML = isFlightAvailable;